# Simple workflow for deploying static content to GitHub Pages
name: Dispatch preview workflow

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Runs on pushes, if all conditions are met:
  push:
    # ... on the master branch ...
    branches:
      - 'preview'
    # ... skip tags only ...
    tags-ignore:
      - '**'
    # ... any of these files changes ...
    paths:
      - 'website/amintiri/**'
      - 'website/evenimente/**'
      - 'website/docs/**'
      - 'website/i18n/**'
      - 'website/src/**'
      - 'website/static/**'
      - 'website/*.js'
      - 'website/*.ts'
      - 'website/*.json'
      - 'website/*.yml'
      - '.github/workflows/dispatch-preview-workflow.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          env | sort
          pwd
          ls -l


      - name: Trigger preview build via curl
        # Note the double apostrophes!
        run: bash scripts/trigger-preview-build.sh ${{ secrets.API_DISPATCH_TOKEN }}
