# Simple workflow for deploying static content to GitHub Pages
name: Publish GitHub Pages

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Runs on pushes, if all conditions are met:
  push:
    # ... on the master branch ...
    branches:
      - 'master'
    # ... skip tags only ...
    tags-ignore:
      - '**'
    # ... any of these files changes ...
    paths:
      - 'website/amintiri/**'
      - 'website/evenimente/**'
      - 'website/docs/**'
      - 'website/i18n/**'
      - 'website/src/**'
      - 'website/static/**'
      - 'website/*.js'
      - 'website/*.ts'
      - 'website/*.json'
      - 'website/*.yml'
      - '.github/workflows/publish-github-pages.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          # The full history, required to compute lastUpdatedAt
          fetch-depth: 0

      - name: Use Nodejs
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci -C website

      - name: Show environment
        run: env | sort | egrep '^[^ \t]+='

      - name: Generate Docusaurus
        run: npm run build -C website

      - name: Prevent robots crawl the preview site
        # https://developers.google.com/search/docs/crawling-indexing/robots/intro
        run: |
          echo 'User-agent: *' > website/build/robots.txt
          echo 'Allow: /' >> website/build/robots.txt
          echo 'Sitemap: https://cronica-it.github.io/sitemap.xml' >> website/build/robots.txt

      - name: Setup Pages
        # https://github.com/actions/configure-pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        # https://github.com/actions/upload-pages-artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: './website/build'

      - name: Deploy to GitHub Pages
        id: deployment
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@v2
